package classes
import interfaces.Android
/*
    Generated By Harry
 */
class GalaxyNote10(screenSize : String) : Phone(screenSize) , Android {

    override fun callGoogleAssistant() {
        println("Launching Google Assistant on Galaxy Note 10")
    }

}