package classes
import interfaces.IOS
/*
    Generated By Harry
 */
class IPadPro(screenSize : String) : Tablet(screenSize) , IOS {

    override fun callSiri() {
        println("Hey Siri....How's the weather?")
    }

}