package classes
import interfaces.IOS
/*
    Generated By Harry
 */
class Iphone11(screenSize : String) : Phone(screenSize) , IOS {

    override fun callSiri() {
        println("Hey Siri.. How's the weather?")
    }

}