package classes
/*
    Generated By Harry
 */
class Person(var firstName : String, var lastName : String) {

    private var age: Int = 0

    //Secondary Constructor
    constructor(firstName: String, lastName: String, age: Int) : this(firstName, lastName) {
        this.age = age
    }
}
