package classes
/*
    Generated By Harry
 */
open class SmartDevice(private val screenSize : String){

    fun takePicture() {
        println("Chalek! You just took a picture!")
    }

    fun connectToInternet()
    {
        println("You are now connected to the Internet")
    }

}


